# Generated by Django 5.1.2 on 2024-11-08 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefCommodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'SupIm'), (2, 'Demand'), (3, 'Stock'), (4, 'Env'), (5, 'Buy'), (6, 'Sell')])),
                ('price', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('maxperhour', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefDemand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('steps', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DefProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instcap', models.FloatField()),
                ('caplo', models.FloatField()),
                ('capup', models.FloatField()),
                ('maxgrad', models.FloatField()),
                ('minfraction', models.FloatField()),
                ('invcost', models.FloatField()),
                ('fixcost', models.FloatField()),
                ('varcost', models.FloatField()),
                ('wacc', models.FloatField()),
                ('deprecation', models.FloatField()),
                ('areapercap', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instcapc', models.IntegerField()),
                ('caploc', models.IntegerField()),
                ('capupc', models.IntegerField()),
                ('instcapp', models.IntegerField()),
                ('caplop', models.IntegerField()),
                ('capupp', models.IntegerField()),
                ('effin', models.FloatField()),
                ('effout', models.FloatField()),
                ('invcostp', models.IntegerField()),
                ('invcostc', models.FloatField()),
                ('fixcostp', models.IntegerField()),
                ('fixcostc', models.FloatField()),
                ('varcostp', models.FloatField()),
                ('varcostc', models.IntegerField()),
                ('wacc', models.FloatField()),
                ('deprecation', models.IntegerField()),
                ('init', models.FloatField()),
                ('discharge', models.FloatField()),
                ('epratio', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefSuplm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('defcommodity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.defcommodity')),
                ('default', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='projects.defcommodity')),
            ],
            bases=('projects.defcommodity',),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('defprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.defprocess')),
                ('default', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='projects.defprocess')),
            ],
            bases=('projects.defprocess',),
        ),
        migrations.CreateModel(
            name='DefProcessCommodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.IntegerField(choices=[(1, 'In'), (2, 'Out')])),
                ('ratio', models.FloatField()),
                ('ratiomin', models.FloatField(null=True)),
                ('def_commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.defcommodity')),
                ('def_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.defprocess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('co2limit', models.BigIntegerField()),
                ('costlimit', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('long', models.DecimalField(decimal_places=9, max_digits=12)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transmission', models.IntegerField(choices=[(1, 'hvac')])),
                ('eff', models.FloatField()),
                ('invcost', models.IntegerField()),
                ('fixcost', models.IntegerField()),
                ('varcost', models.FloatField()),
                ('instcap', models.IntegerField()),
                ('caplo', models.IntegerField()),
                ('capup', models.IntegerField()),
                ('wacc', models.FloatField()),
                ('deprecation', models.FloatField()),
                ('reactance', models.FloatField()),
                ('difflimit', models.FloatField()),
                ('basevoltage', models.FloatField()),
                ('sitein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transmissions', to='projects.site')),
                ('siteout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transmissions', to='projects.site')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commodity')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site'),
        ),
        migrations.CreateModel(
            name='BuySellPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buy', models.JSONField()),
                ('sell', models.JSONField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('defdemand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.defdemand')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commodity')),
                ('default', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='projects.defdemand')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site')),
            ],
            bases=('projects.defdemand',),
        ),
        migrations.CreateModel(
            name='TimeVarEff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steps', models.FloatField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessCommodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.IntegerField(choices=[(1, 'In'), (2, 'Out')])),
                ('ratio', models.FloatField()),
                ('ratiomin', models.FloatField(null=True)),
                ('default', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='projects.defprocesscommodity')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commodity')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='process',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site'),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('defstorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.defstorage')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commodity')),
                ('default', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='projects.defstorage')),
            ],
            bases=('projects.defstorage',),
        ),
        migrations.CreateModel(
            name='Suplm',
            fields=[
                ('defsuplm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.defsuplm')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commodity')),
                ('default', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='projects.defsuplm')),
            ],
            bases=('projects.defsuplm',),
        ),
    ]
