# Generated by Django 5.1.4 on 2025-02-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='maxperhour',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='defcommodity',
            name='max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='defcommodity',
            name='maxperhour',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='defcommodity',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
