# Generated by Django 5.1.3 on 2024-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area',
            field=models.IntegerField(null=True),
        ),
    ]
