# Generated by Django 5.1.4 on 2025-02-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_commodity_max_alter_commodity_maxperhour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='unitC',
            field=models.TextField(default='kWh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity',
            name='unitR',
            field=models.TextField(default='kW'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defcommodity',
            name='unitC',
            field=models.TextField(default='kWh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defcommodity',
            name='unitR',
            field=models.TextField(default='kW'),
            preserve_default=False,
        ),
    ]
