# Generated by Django 5.1.4 on 2025-03-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_commodity_unitc_commodity_unitr_defcommodity_unitc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area',
            field=models.BigIntegerField(null=True),
        ),
    ]
