# Generated by Django 5.1.3 on 2024-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_simulationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='config',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='log',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='status',
            field=models.IntegerField(choices=[(1, 'Optimal'), (2, 'Infeasible'), (3, 'Error')], null=True),
        ),
    ]
