# Generated by Django 5.1.4 on 2025-05-02 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_defstorage_caploc_alter_defstorage_caplop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buysellprice',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='buysellprice',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='sitein',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='siteout',
        ),
        migrations.AddField(
            model_name='buysellprice',
            name='steps',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buysellprice',
            name='type',
            field=models.IntegerField(choices=[(1, 'buy'), (2, 'sell')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmission',
            name='commodityin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transmissions', to='projects.commodity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmission',
            name='commodityout',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transmissions', to='projects.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transmission',
            name='basevoltage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='difflimit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='reactance',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='DSM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delay', models.IntegerField()),
                ('eff', models.FloatField()),
                ('recov', models.IntegerField()),
                ('capmaxdo', models.FloatField()),
                ('capmaxup', models.FloatField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commodity')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site')),
            ],
        ),
    ]
