# Generated by Django 5.1.4 on 2025-05-21 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_defstorage_caploc_alter_defstorage_caplop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delay', models.IntegerField()),
                ('eff', models.FloatField()),
                ('recov', models.IntegerField()),
                ('capmaxdo', models.FloatField()),
                ('capmaxup', models.FloatField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commodity')),
            ],
        ),
        migrations.DeleteModel(
            name='BuySellPrice',
        ),
        migrations.DeleteModel(
            name='Transmission',
        ),
        migrations.DeleteModel(
            name='TimeVarEff',
        ),
    ]
