# Generated by Django 5.1.4 on 2025-05-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_buysellprice_buy_remove_buysellprice_sell_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transmission',
            old_name='transmission',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='timevareff',
            name='steps',
        ),
    ]
