# Generated by Django 5.1.4 on 2025-05-21 21:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_transmission_commodity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuySellPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'buy'), (2, 'sell')])),
                ('steps', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='TimeVarEff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steps', models.JSONField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.process')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'hvac')])),
                ('eff', models.FloatField()),
                ('invcost', models.FloatField()),
                ('fixcost', models.FloatField()),
                ('varcost', models.FloatField()),
                ('instcap', models.FloatField()),
                ('caplo', models.FloatField()),
                ('capup', models.FloatField()),
                ('wacc', models.FloatField()),
                ('depreciation', models.FloatField()),
                ('reactance', models.FloatField(null=True)),
                ('difflimit', models.FloatField(null=True)),
                ('basevoltage', models.FloatField(null=True)),
                ('commodityin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transmissions', to='projects.commodity')),
                ('commodityout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transmissions', to='projects.commodity')),
            ],
        ),
    ]
