# Generated by Django 5.1.4 on 2025-05-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_transmission_transmission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timevareff',
            name='steps',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
