# Generated by Django 5.1.4 on 2025-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_buysellprice_timevareff_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
