# Generated by Django 5.1.4 on 2025-06-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_simulationresult_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buysellprice',
            name='type',
        ),
    ]
