# Generated by Django 5.1.4 on 2025-05-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_timevareff_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='commodityout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transmissions', to='projects.commodity'),
        ),
    ]
