# Generated by Django 5.1.4 on 2025-07-07 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_buysellprice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefProject',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DefProjectLoaded',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.defproject')),
            ],
        ),
    ]
