# Generated by Django 5.1.4 on 2025-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_buysellprice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='type',
            field=models.IntegerField(choices=[(1, 'hvac'), (2, 'pipe')]),
        ),
    ]
