# Generated by Django 5.1.4 on 2025-05-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_transmission_commodityout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsm',
            name='site',
        ),
        migrations.RemoveField(
            model_name='timevareff',
            name='site',
        ),
    ]
